/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import jflex.AnalizadorLexico;
import jflex.Token;
import jflex.TokenConstant;
import parser.Data;
import parser.ModifiedTable;
import parser.StateAnalyzer;
import parser.SyntaxError;
import parser.SyntaxException;
import parser.Table;

/**
 *
 * @author Carlos Cotom
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    private ArrayList<Token> tokensErrorLexico;
    private Data data;

    private File archivoActual;

    private final DefaultTableModel modelTableErroresLexicos;
    private final DefaultTableModel modelTableErroresSintacticos;
    private final DefaultTableModel modelTableTablasEncontradas;
    private final DefaultTableModel modelTableTablasModificadas;
    private final DefaultTableModel modelTablaNumeroOperaciones;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        this.modelTableErroresLexicos = new DefaultTableModel();
        this.modelTableErroresSintacticos = new DefaultTableModel();
        this.modelTableTablasEncontradas = new DefaultTableModel();
        this.modelTableTablasModificadas = new DefaultTableModel();
        this.modelTablaNumeroOperaciones = new DefaultTableModel();
        initComponents();
        this.iniciarTableros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        dlgReporteErrorLexico = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblErroresLexicos = new javax.swing.JTable();
        dlgReporteErrorSintactico = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblErroresSintacticos = new javax.swing.JTable();
        dlgReporteTablasEncontradas = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTablasEncontradas = new javax.swing.JTable();
        dlgReporteTablasModificadas = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTablasModificadas = new javax.swing.JTable();
        dlgReporteNumeroOperaciones = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumeroOperaciones = new javax.swing.JTable();
        btnAnalizar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txaCodigo = new javax.swing.JTextPane();
        btnLimpiar = new javax.swing.JButton();
        lblFilaColumna = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCarga = new javax.swing.JMenuItem();
        mnuGuardar = new javax.swing.JMenuItem();
        mnuGuardarComo = new javax.swing.JMenuItem();
        mnuGrafico = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuErrorLexico = new javax.swing.JMenuItem();
        mnuErrorSintactico = new javax.swing.JMenuItem();
        mnuTablasEncontradas = new javax.swing.JMenuItem();
        mnuTablasModificadas = new javax.swing.JMenuItem();
        mnuNumeroOperaciones = new javax.swing.JMenuItem();

        dlgReporteErrorLexico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporteErrorLexico.setTitle("Reporte Errores Lexicos");
        dlgReporteErrorLexico.setMinimumSize(new java.awt.Dimension(600, 300));

        tblErroresLexicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Token", "Linea", "Columna", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblErroresLexicos);

        javax.swing.GroupLayout dlgReporteErrorLexicoLayout = new javax.swing.GroupLayout(dlgReporteErrorLexico.getContentPane());
        dlgReporteErrorLexico.getContentPane().setLayout(dlgReporteErrorLexicoLayout);
        dlgReporteErrorLexicoLayout.setHorizontalGroup(
            dlgReporteErrorLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteErrorLexicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReporteErrorLexicoLayout.setVerticalGroup(
            dlgReporteErrorLexicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteErrorLexicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        dlgReporteErrorSintactico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporteErrorSintactico.setTitle("Reporte de Errores Sintacticos");
        dlgReporteErrorSintactico.setMinimumSize(new java.awt.Dimension(700, 300));

        tblErroresSintacticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Token", "Tipo Token", "Linea", "Columna", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblErroresSintacticos);

        javax.swing.GroupLayout dlgReporteErrorSintacticoLayout = new javax.swing.GroupLayout(dlgReporteErrorSintactico.getContentPane());
        dlgReporteErrorSintactico.getContentPane().setLayout(dlgReporteErrorSintacticoLayout);
        dlgReporteErrorSintacticoLayout.setHorizontalGroup(
            dlgReporteErrorSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteErrorSintacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReporteErrorSintacticoLayout.setVerticalGroup(
            dlgReporteErrorSintacticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteErrorSintacticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        dlgReporteTablasEncontradas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporteTablasEncontradas.setTitle("Reporte de Tablas Encontradas");
        dlgReporteTablasEncontradas.setMinimumSize(new java.awt.Dimension(500, 300));

        tblTablasEncontradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tabla", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblTablasEncontradas);

        javax.swing.GroupLayout dlgReporteTablasEncontradasLayout = new javax.swing.GroupLayout(dlgReporteTablasEncontradas.getContentPane());
        dlgReporteTablasEncontradas.getContentPane().setLayout(dlgReporteTablasEncontradasLayout);
        dlgReporteTablasEncontradasLayout.setHorizontalGroup(
            dlgReporteTablasEncontradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteTablasEncontradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReporteTablasEncontradasLayout.setVerticalGroup(
            dlgReporteTablasEncontradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteTablasEncontradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        dlgReporteTablasModificadas.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporteTablasModificadas.setTitle("Reporte de Tablas Modificadas");
        dlgReporteTablasModificadas.setMinimumSize(new java.awt.Dimension(500, 300));

        tblTablasModificadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Modificacion", "Tabla", "Linea", "Columna"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblTablasModificadas);

        javax.swing.GroupLayout dlgReporteTablasModificadasLayout = new javax.swing.GroupLayout(dlgReporteTablasModificadas.getContentPane());
        dlgReporteTablasModificadas.getContentPane().setLayout(dlgReporteTablasModificadasLayout);
        dlgReporteTablasModificadasLayout.setHorizontalGroup(
            dlgReporteTablasModificadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteTablasModificadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReporteTablasModificadasLayout.setVerticalGroup(
            dlgReporteTablasModificadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteTablasModificadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        dlgReporteNumeroOperaciones.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        dlgReporteNumeroOperaciones.setTitle("Reporte de Numero de Operaciones");
        dlgReporteNumeroOperaciones.setMinimumSize(new java.awt.Dimension(400, 300));

        tblNumeroOperaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Operacion", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(tblNumeroOperaciones);

        javax.swing.GroupLayout dlgReporteNumeroOperacionesLayout = new javax.swing.GroupLayout(dlgReporteNumeroOperaciones.getContentPane());
        dlgReporteNumeroOperaciones.getContentPane().setLayout(dlgReporteNumeroOperacionesLayout);
        dlgReporteNumeroOperacionesLayout.setHorizontalGroup(
            dlgReporteNumeroOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteNumeroOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgReporteNumeroOperacionesLayout.setVerticalGroup(
            dlgReporteNumeroOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgReporteNumeroOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WorkBench");
        setMinimumSize(new java.awt.Dimension(1000, 600));

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        txaCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txaCodigoCaretUpdate(evt);
            }
        });
        jScrollPane6.setViewportView(txaCodigo);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblFilaColumna.setText(".");

        jMenu1.setText("Archivo");

        mnuCarga.setText("Cargar");
        mnuCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCargaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCarga);

        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGuardar);

        mnuGuardarComo.setText("Guardar como...");
        mnuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGuardarComo);

        jMenuBar1.add(jMenu1);

        mnuGrafico.setText("Grafico");
        jMenuBar1.add(mnuGrafico);

        jMenu3.setText("Reporte");

        mnuErrorLexico.setText("Error Lexico");
        mnuErrorLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuErrorLexicoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuErrorLexico);

        mnuErrorSintactico.setText("Error Sintacticos");
        mnuErrorSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuErrorSintacticoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuErrorSintactico);

        mnuTablasEncontradas.setText("Tablas Encontradas");
        mnuTablasEncontradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTablasEncontradasActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTablasEncontradas);

        mnuTablasModificadas.setText("Tablas Modificadas");
        mnuTablasModificadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTablasModificadasActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTablasModificadas);

        mnuNumeroOperaciones.setText("Numero Operaciones");
        mnuNumeroOperaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNumeroOperacionesActionPerformed(evt);
            }
        });
        jMenu3.add(mnuNumeroOperaciones);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnalizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 823, Short.MAX_VALUE)
                        .addComponent(lblFilaColumna)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizar)
                    .addComponent(btnLimpiar)
                    .addComponent(lblFilaColumna))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        this.tokensErrorLexico = new ArrayList<>();
        ArrayList<Token> tokensAnalizados = new ArrayList<>();
        try {
            AnalizadorLexico analizador = new AnalizadorLexico(new StringReader(this.txaCodigo.getText()));
            analizador.pintor.establecerEstilo(this.txaCodigo.getText());
            this.txaCodigo.setDocument(analizador.pintor.textPane.getDocument());
            while (!analizador.yyatEOF()) {
                Token tokenActual = analizador.yylex();
                System.out.println(tokenActual.toString());
                if (tokenActual.getTipoToken() == TokenConstant.ERROR) {
                    this.tokensErrorLexico.add(tokenActual);
                    continue;
                }
                if (tokenActual.getTipoToken() == TokenConstant.COMENTARIO) {
                    continue;
                }
                tokensAnalizados.add(tokenActual);
            }
            System.out.println("");
        } catch (IOException ex) {
            System.out.println("Error " + ex);
        }
        try {
            data = new Data(tokensAnalizados);
            StateAnalyzer stateAnalyzer = new StateAnalyzer(data);
            stateAnalyzer.analyze();
        } catch (SyntaxException e) {
            JOptionPane.showMessageDialog(this, "Analisis Finalizado", "", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        this.data = null;
        this.txaCodigo.setText("");
        Style defaultStyle = this.txaCodigo.addStyle("DefaultStyle", null);
        StyleConstants.setForeground(defaultStyle, Color.black);
        this.txaCodigo.setCharacterAttributes(defaultStyle, true);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void mnuErrorLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuErrorLexicoActionPerformed
        this.vaciarTablaErroresLexicos();
        this.llenarTablaErroresLexicos();
        this.dlgReporteErrorLexico.setVisible(true);
        this.dlgReporteErrorLexico.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuErrorLexicoActionPerformed

    private void mnuCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCargaActionPerformed
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.txt", "txt");
        jFileChooser1.setFileFilter(filtro);
        jFileChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser1.setVisible(true);
        int resultado = jFileChooser1.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            this.archivoActual = jFileChooser1.getSelectedFile();
            try (BufferedReader reader = new BufferedReader(new FileReader(this.archivoActual))) {
                this.txaCodigo.read(reader, null);
            } catch (IOException e) {
                System.out.println("Error al imprimir el codigo fuente: " + e);
            }
        }
    }//GEN-LAST:event_mnuCargaActionPerformed

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
        if (this.archivoActual == null) {
            JFileChooser fileChooser = new JFileChooser();
            if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                this.archivoActual = fileChooser.getSelectedFile();
                escribirArchivoNuevo(this.archivoActual);
            }
        } else {
            this.escribirArchivoNuevo(archivoActual);
        }
    }//GEN-LAST:event_mnuGuardarActionPerformed

    private void mnuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarComoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.archivoActual = fileChooser.getSelectedFile();
            escribirArchivoNuevo(this.archivoActual);
        }
    }//GEN-LAST:event_mnuGuardarComoActionPerformed

    private void txaCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txaCodigoCaretUpdate
        try {
            //Obtener la posicion del caracter actual en el JTextPane
            int posicion = evt.getDot();
            //Obtener el documento y el texto actual
            Document doc = this.txaCodigo.getDocument();
            String text = doc.getText(0, doc.getLength());
            int line = 0;
            int column = 0;
            //Recorrer el texto hasta la posicion del caracter para contar las lineas y clumnas
            for (int i = 0; i < posicion; i++) {
                if (text.charAt(i) == '\n') {
                    line++;
                    column = 0;
                } else {
                    column++;
                }
            }
            //Mostrar el numero de fila y columna actual del cursor
            this.lblFilaColumna.setText("Fila: " + line + " Columna: " + column);
        } catch (BadLocationException e) {
            System.out.println("Error para la actuizacion de fila columna: " + e);
        }
    }//GEN-LAST:event_txaCodigoCaretUpdate

    private void mnuErrorSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuErrorSintacticoActionPerformed
        this.vaciarTablaErroresSintacticos();
        this.llenarTablaErroresSintacticos();
        this.dlgReporteErrorSintactico.setVisible(true);
        this.dlgReporteErrorSintactico.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuErrorSintacticoActionPerformed

    private void mnuTablasEncontradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTablasEncontradasActionPerformed
        this.vaciarTableTablasEncontradas();
        this.llenarTableTablasEncontradas();
        this.dlgReporteTablasEncontradas.setVisible(true);
        this.dlgReporteTablasEncontradas.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuTablasEncontradasActionPerformed

    private void mnuTablasModificadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTablasModificadasActionPerformed
        this.vaciarTableTablasModificadas();
        this.llenarTableTablasModificadas();
        this.dlgReporteTablasModificadas.setVisible(true);
        this.dlgReporteTablasModificadas.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuTablasModificadasActionPerformed

    private void mnuNumeroOperacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNumeroOperacionesActionPerformed
        this.vaciarTablaNumeroOperaciones();
        this.llenarTablaNumeroOperaciones();
        this.dlgReporteNumeroOperaciones.setVisible(true);
        this.dlgReporteNumeroOperaciones.setLocationRelativeTo(this);
    }//GEN-LAST:event_mnuNumeroOperacionesActionPerformed

    private void escribirArchivoNuevo(File file) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(this.txaCodigo.getText());
            JOptionPane.showMessageDialog(this, "Archivo guardado con Exito");
        } catch (IOException e) {
            System.out.println("Error al guardar el archivo: " + e);
        }
    }

    /**
     * Metodo que le da a las Tablas de Reportes en la interfaz el modelo
     * adecuado para su visualizacion
     */
    private void iniciarTableros() {
        this.tblErroresLexicos.setModel(modelTableErroresLexicos);
        this.modelTableErroresLexicos.addColumn("Token");
        this.modelTableErroresLexicos.addColumn("Linea");
        this.modelTableErroresLexicos.addColumn("Columna");
        this.modelTableErroresLexicos.addColumn("Descripcion");

        this.tblErroresSintacticos.setModel(modelTableErroresSintacticos);
        this.modelTableErroresSintacticos.addColumn("Token");
        this.modelTableErroresSintacticos.addColumn("Tipo Token");
        this.modelTableErroresSintacticos.addColumn("Linea");
        this.modelTableErroresSintacticos.addColumn("Columna");
        this.modelTableErroresSintacticos.addColumn("Descripcion");

        this.tblTablasEncontradas.setModel(modelTableTablasEncontradas);
        this.modelTableTablasEncontradas.addColumn("Tabla");
        this.modelTableTablasEncontradas.addColumn("Linea");
        this.modelTableTablasEncontradas.addColumn("Columna");

        this.tblTablasModificadas.setModel(modelTableTablasModificadas);
        this.modelTableTablasModificadas.addColumn("Modificacion");
        this.modelTableTablasModificadas.addColumn("Tabla");
        this.modelTableTablasModificadas.addColumn("Linea");
        this.modelTableTablasModificadas.addColumn("Columna");

        this.tblNumeroOperaciones.setModel(modelTablaNumeroOperaciones);
        this.modelTablaNumeroOperaciones.addColumn("Operacion");
        this.modelTablaNumeroOperaciones.addColumn("Cantidad");
    }

    /**
     * Metodo que limpia la Tabla de Reporte en la Interfaz para no tener
     * problemas de colapsos
     */
    private void vaciarTablaErroresLexicos() {
        this.tblErroresLexicos.removeAll();
        int filasTabla = this.modelTableErroresLexicos.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modelTableErroresLexicos.removeRow(0);
            }
        }
    }

    /**
     * Metodo que muestra en la Tabla de Reporte en la interfaz los datos de
     * cada Token que esta se encontro en el analisis
     *
     * @param datos son los datos de cada token registrados
     */
    private void llenarTablaErroresLexicos() {
        this.tblErroresLexicos.setModel(this.modelTableErroresLexicos);
        Object[] fila;
        for (int i = 0; i < this.tokensErrorLexico.size(); i++) {
            fila = new Object[4];
            fila[0] = this.tokensErrorLexico.get(i).getLexema();
            fila[1] = this.tokensErrorLexico.get(i).getLinea();
            fila[2] = this.tokensErrorLexico.get(i).getColumna();
            fila[3] = "Token no Reconocido";
            this.modelTableErroresLexicos.addRow(fila);
        }
    }

    /**
     * Metodo que limpia la Tabla de Reporte en la Interfaz para no tener
     * problemas de colapsos
     */
    private void vaciarTablaErroresSintacticos() {
        this.tblErroresSintacticos.removeAll();
        int filasTabla = this.modelTableErroresSintacticos.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modelTableErroresSintacticos.removeRow(0);
            }
        }
    }

    /**
     * Metodo que muestra en la Tabla de Reporte en la interfaz los datos de
     * cada Token que esta se encontro en el analisis
     *
     * @param datos son los datos de cada token registrados
     */
    private void llenarTablaErroresSintacticos() {
        this.tblErroresSintacticos.setModel(this.modelTableErroresSintacticos);
        Object[] fila;
        ArrayList<SyntaxError> errores = this.data.getSyntaxErrors();
        for (int i = 0; i < errores.size(); i++) {
            fila = new Object[5];
            fila[0] = errores.get(i).getErrorToken().getLexema();
            fila[1] = errores.get(i).getErrorToken().getTipoToken();
            fila[2] = errores.get(i).getErrorToken().getLinea();
            fila[3] = errores.get(i).getErrorToken().getColumna();
            fila[4] = errores.get(i).getDescription();
            this.modelTableErroresSintacticos.addRow(fila);
        }
    }

    /**
     * Metodo que limpia la Tabla de Reporte en la Interfaz para no tener
     * problemas de colapsos
     */
    private void vaciarTableTablasEncontradas() {
        this.tblTablasEncontradas.removeAll();
        int filasTabla = this.modelTableTablasEncontradas.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modelTableTablasEncontradas.removeRow(0);
            }
        }
    }

    /**
     * Metodo que muestra en la Tabla de Reporte en la interfaz los datos de
     * cada Token que esta se encontro en el analisis
     *
     * @param datos son los datos de cada token registrados
     */
    private void llenarTableTablasEncontradas() {
        this.tblTablasEncontradas.setModel(this.modelTableTablasEncontradas);
        Object[] fila;
        ArrayList<Table> tablas = this.data.getTables();
        for (int i = 0; i < tablas.size(); i++) {
            fila = new Object[3];
            fila[0] = tablas.get(i).getName().getLexema();
            fila[1] = tablas.get(i).getName().getLinea();
            fila[2] = tablas.get(i).getName().getColumna();
            this.modelTableTablasEncontradas.addRow(fila);
        }
    }

    /**
     * Metodo que limpia la Tabla de Reporte en la Interfaz para no tener
     * problemas de colapsos
     */
    private void vaciarTableTablasModificadas() {
        this.tblTablasModificadas.removeAll();
        int filasTabla = this.modelTableTablasModificadas.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modelTableTablasModificadas.removeRow(0);
            }
        }
    }

    /**
     * Metodo que muestra en la Tabla de Reporte en la interfaz los datos de
     * cada Token que esta se encontro en el analisis
     *
     * @param datos son los datos de cada token registrados
     */
    private void llenarTableTablasModificadas() {
        this.tblTablasModificadas.setModel(this.modelTableTablasModificadas);
        Object[] fila;
        ArrayList<ModifiedTable> modificaciones = this.data.getModifiedTables();
        for (int i = 0; i < modificaciones.size(); i++) {
            fila = new Object[4];
            fila[0] = modificaciones.get(i).getKey().getLexema();
            fila[1] = modificaciones.get(i).getName().getLexema();
            fila[2] = modificaciones.get(i).getKey().getLinea();
            fila[3] = modificaciones.get(i).getKey().getColumna();
            this.modelTableTablasModificadas.addRow(fila);
        }
    }

    /**
     * Metodo que limpia la Tabla de Reporte en la Interfaz para no tener
     * problemas de colapsos
     */
    private void vaciarTablaNumeroOperaciones() {
        this.tblNumeroOperaciones.removeAll();
        int filasTabla = this.modelTablaNumeroOperaciones.getRowCount();
        if (filasTabla != 0) {
            for (int i = 0; i < filasTabla; i++) {
                this.modelTablaNumeroOperaciones.removeRow(0);
            }
        }
    }

    /**
     * Metodo que muestra en la Tabla de Reporte en la interfaz los datos de
     * cada Token que esta se encontro en el analisis
     *
     * @param datos son los datos de cada token registrados
     */
    private void llenarTablaNumeroOperaciones() {
        this.tblNumeroOperaciones.setModel(this.modelTablaNumeroOperaciones);
        Object[] fila;
        fila = new Object[2];
        fila[0] = "CREATE";
        fila[1] = this.data.getCreates();
        this.modelTablaNumeroOperaciones.addRow(fila);
        fila = new Object[2];
        fila[0] = "DELETE";
        fila[1] = this.data.getDeletes();
        this.modelTablaNumeroOperaciones.addRow(fila);
        fila = new Object[2];
        fila[0] = "UPDATE";
        fila[1] = this.data.getUpdates();
        this.modelTablaNumeroOperaciones.addRow(fila);
        fila = new Object[2];
        fila[0] = "SELECT";
        fila[1] = this.data.getSelects();
        this.modelTablaNumeroOperaciones.addRow(fila);
        fila = new Object[2];
        fila[0] = "ALTER";
        fila[1] = this.data.getAlters();
        this.modelTablaNumeroOperaciones.addRow(fila);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JDialog dlgReporteErrorLexico;
    private javax.swing.JDialog dlgReporteErrorSintactico;
    private javax.swing.JDialog dlgReporteNumeroOperaciones;
    private javax.swing.JDialog dlgReporteTablasEncontradas;
    private javax.swing.JDialog dlgReporteTablasModificadas;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblFilaColumna;
    private javax.swing.JMenuItem mnuCarga;
    private javax.swing.JMenuItem mnuErrorLexico;
    private javax.swing.JMenuItem mnuErrorSintactico;
    private javax.swing.JMenu mnuGrafico;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuGuardarComo;
    private javax.swing.JMenuItem mnuNumeroOperaciones;
    private javax.swing.JMenuItem mnuTablasEncontradas;
    private javax.swing.JMenuItem mnuTablasModificadas;
    private javax.swing.JTable tblErroresLexicos;
    private javax.swing.JTable tblErroresSintacticos;
    private javax.swing.JTable tblNumeroOperaciones;
    private javax.swing.JTable tblTablasEncontradas;
    private javax.swing.JTable tblTablasModificadas;
    private javax.swing.JTextPane txaCodigo;
    // End of variables declaration//GEN-END:variables
}
